[general]
destination = "$HOME/.config/hypr/monitors.conf"
debounce_time_ms = 1000
# post_apply_exec = "hyprctl reload"  # uncomment if needed

[notifications]
disabled = false
timeout_ms = 3000

[fallback_profile]
name = "laptop"  # ignored by hyprdynamicmonitors (hardcoded as "fallback")
config_file = "hyprconfigs/laptop.conf"
config_file_type = "static"

[profiles.laptop-battery]
config_file = "hyprconfigs/laptop-battery.conf"
config_file_type = "static"
[profiles.laptop-battery.conditions]
power_state = "BAT"
[[profiles.laptop-battery.conditions.required_monitors]]
description = "California Institute"
match_description_using_regex = true

# [profiles.laptop-arzopa]
# config_file = "hyprconfigs/laptop-arzopa.conf"
# config_file_type = "static"
# [[profiles.laptop-arzopa.conditions.required_monitors]]
# description = "California Institute"
# match_description_using_regex = true
# [[profiles.laptop-arzopa.conditions.required_monitors]]
# description = "ARZOPA"
# match_description_using_regex = true

[profiles.iiyama]
config_file = "hyprconfigs/external.go.tmpl"
config_file_type = "template"
[profiles.iiyama.static_template_values]
res = "3440x1440"
refresh_ac = "179.98"
refresh_bat = "60"
scale = "1.25"
[[profiles.iiyama.conditions.required_monitors]]
description = "PL3481WQ"
match_description_using_regex = true
monitor_tag = "external"

[profiles.asus]
config_file = "hyprconfigs/external.go.tmpl"
config_file_type = "template"
[profiles.asus.static_template_values]
res = "3440x1440"
refresh_ac = "100"
refresh_bat = "60"
scale = "1.25"
[[profiles.asus.conditions.required_monitors]]
description = "VG34VQ"
match_description_using_regex = true
monitor_tag = "external"

[profiles.arzopa]
config_file = "hyprconfigs/external.go.tmpl"
config_file_type = "template"
[profiles.arzopa.static_template_values]
res = "1920x1080"
refresh_ac = "60"
refresh_bat = "60"
scale = "1.0"
[[profiles.arzopa.conditions.required_monitors]]
description = "ARZOPA"
match_description_using_regex = true
monitor_tag = "external"

[profiles.samsung]
config_file = "hyprconfigs/external.go.tmpl"
config_file_type = "template"
[profiles.samsung.static_template_values]
res = "1920x1080"
refresh_ac = "120"
refresh_bat = "60"
scale = "1.0"
[[profiles.samsung.conditions.required_monitors]]
description = "Samsung"
match_description_using_regex = true
monitor_tag = "external"
