bookmarks = [
    "/home/kicky/dotfiles",
    "/home/kicky/Work/tries",
    "/home/kicky/work/06-resources/Script Neptun",
    "/home/kicky/dev",
]

[[search_dirs]]
path = "/home/kicky/Work/tries"
depth = 10

[[search_dirs]]
path = "/home/kicky/dev"
depth = 10
