[tools]
bun = "latest"
go = "1.23"
jq = "latest"
node = "22"
pnpm = "latest"
python = "3.12"
uv = "latest"
eza = "latest"
yq = "latest"
fd = "latest"
lazygit = "latest"
delta = "latest"
ripgrep = "latest"
fzf = "latest"
bat = "latest"
rust = "latest"
deno = "latest"
